# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: ARTIFACT_VERSION
    type: string
    default: major
    values:
      - major
      - minor
      - patch
    displayName: Select the release type. The versioning follows the semantic versioning scheme

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: publish 
    arguments: -r linux-x64 -p:PublishSingleFile=True --self-contained false -o $(Build.ArtifactStagingDirectory)
    projects: '$(Build.SourcesDirectory)/tools/code/extractor/*.csproj'
    publishWebProjects: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'extractor'
    publishLocation: 'Container'

- task: UniversalPackages@0
  displayName: Publish apiops executables to artifact management
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'ESS_API_Management/ESS_API_MANAGEMENT_API_OPS'
    vstsFeedPackagePublish: 'apiops-artifacts'
    packagePublishDescription: 'Compiled customized components of Azure ApiOps'
    versionOption: ${{parameters.ARTIFACT_VERSION}}
